### PR TITLE
Skip alert type postsave during config sync and skip type of alert in block if not present

### LINKED ISSUE #251: Config import failure after initial localgov_alert_banner install
Hello,
I noticed today that config import is failing after installing this module on a fresh (or old) site.  To be certain, I installed a fresh LocalGov site, took a database dump, installed this module, exported all the config, restored the database dump, and finally tried to import the config.

According to the combined [wisdom of Stackoverflow](https://drupal.stackexchange.com/a/302762), one can run `drush config:import` **twice** to get out of this trouble and I can confirm that it actually works.  Although, it would have been better not to run into this issue at all :(

FAO @andybroomfield @finnlewis 

## How to reproduce
```
$ composer create-project localgovdrupal/localgov-project
$ cd localgov-project/
$ > web/sites/default/settings.lando.php
$ drush site:install --yes --db-url=mysql://USERNAME:PASSWD@MYSQL-HOSTNAME/DB-SCHEMA-NAME localgov
$ drush sql:dump --result-file=../post-install-db-dump.sql
$ drush pm:install --yes localgov_alert_banner
$ drush config:export --yes
$ drush sql:drop --yes; drush sql:query --file=../post-install-db-dump.sql
$ drush config:import --yes
+------------+------------------------------------------------------------------------------+-----------+
| Collection | Config                                                                       | Operation |
+------------+------------------------------------------------------------------------------+-----------+
|            | field.storage.localgov_alert_banner.visibility                               | Create    |
|            | field.storage.localgov_alert_banner.link                                     | Create    |
|            | localgov_alert_banner.localgov_alert_banner_type.localgov_alert_banner       | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.visibility           | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.link                 | Create    |
|            | block.block.localgov_alert_banner_base                                       | Create    |
|            | block.block.localgov_alert_banner_scarfolk                                   | Create    |
|            | field.storage.localgov_alert_banner.type_of_alert                            | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.type_of_alert        | Create    |
|            | field.storage.localgov_alert_banner.short_description                        | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.short_description    | Create    |
|            | core.entity_view_display.localgov_alert_banner.localgov_alert_banner.default | Create    |
|            | core.entity_form_display.localgov_alert_banner.localgov_alert_banner.default | Create    |
|            | views.view.localgov_admin_manage_alert_banners                               | Create    |
|            | workflows.workflow.localgov_alert_banners                                    | Create    |
|            | user.role.emergency_publisher                                                | Create    |
|            | system.action.user_remove_role_action.emergency_publisher                    | Create    |
|            | system.action.user_add_role_action.emergency_publisher                       | Create    |
|            | core.extension                                                               | Update    |
|            | user.role.anonymous                                                          | Update    |
|            | user.role.authenticated                                                      | Update    |
+------------+------------------------------------------------------------------------------+-----------+

 // Import the listed configuration changes?: yes.   

 [notice] Synchronized extensions: install condition_field.
 [notice] Synchronized extensions: install localgov_alert_banner.
 [notice] Synchronized configuration: create field.storage.localgov_alert_banner.visibility.
 [notice] Synchronized configuration: create field.storage.localgov_alert_banner.link.
 [notice] Synchronized configuration: create localgov_alert_banner.localgov_alert_banner_type.localgov_alert_banner.
 [notice] Synchronized configuration: create field.field.localgov_alert_banner.localgov_alert_banner.visibility.
 [notice] Synchronized configuration: create field.field.localgov_alert_banner.localgov_alert_banner.link.
 [notice] Synchronized configuration: create block.block.localgov_alert_banner_base.
 [notice] Synchronized configuration: create block.block.localgov_alert_banner_scarfolk.
 [notice] Synchronized configuration: create field.storage.localgov_alert_banner.type_of_alert.
 [notice] Synchronized configuration: create field.field.localgov_alert_banner.localgov_alert_banner.type_of_alert.
 [notice] Synchronized configuration: create field.storage.localgov_alert_banner.short_description.
 [notice] Synchronized configuration: create field.field.localgov_alert_banner.localgov_alert_banner.short_description.
 [notice] Synchronized configuration: create core.entity_view_display.localgov_alert_banner.localgov_alert_banner.default.
 [notice] Synchronized configuration: create core.entity_form_display.localgov_alert_banner.localgov_alert_banner.default.
 [notice] Synchronized configuration: create views.view.localgov_admin_manage_alert_banners.
 [notice] Synchronized configuration: create workflows.workflow.localgov_alert_banners.
 [notice] Synchronized configuration: create user.role.emergency_publisher.
 [notice] Synchronized configuration: create system.action.user_remove_role_action.emergency_publisher.
 [notice] Synchronized configuration: create system.action.user_add_role_action.emergency_publisher.
 [notice] Synchronized configuration: update user.role.anonymous.
 [notice] Synchronized configuration: update user.role.authenticated.
 [notice] Finalizing configuration synchronization.
 [error]  Drupal\Core\Config\ConfigException: Errors occurred during import in Drush\Drupal\Commands\config\ConfigImportCommands->doImport() (line 310 of /dev/shm/localgov-project/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php). 

In ConfigImportCommands.php line 324:
                                                                                                                              
  The import failed due to the following reasons:                                                                             
  Deleted and replaced configuration entity "field.field.localgov_alert_banner.localgov_alert_banner.visibility"              
  Unexpected error during import with operation create for field.field.localgov_alert_banner.localgov_alert_banner.visibilit  
  y: Attempted to create an instance of field with name visibility on entity type localgov_alert_banner when the field stora  
  ge does not exist.                                                                                                          
  Unexpected error during import with operation create for block.block.localgov_alert_banner_base: &#039;type_of_alert&#039;  
   not found                                                                                                                  
  Unexpected error during import with operation create for block.block.localgov_alert_banner_scarfolk: &#039;type_of_alert&#  
  039; not found                                                                                                                                                             
```

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #251

During config sync operations, if creating a new alert banner type the visibility field will try to be created, even though that is part of config.

This checks if the isSyncing flag is set and skips over the postSave actions as we assume they are part of the config being imported.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Hi Andy,
Thanks for such a prompt response.  I have tried the fix on both a fresh site and and existing site.  This fix has resolved the issue with the visibility field.  But the block config imports are still failing :(  This is the final error message I am seeing on a fresh site:

```
In ConfigImportCommands.php line 324:                                                                                       
                                                                                                                              
    The import failed due to the following reasons:                                                                           
    Unexpected error during import with operation create for block.block.localgov_alert_banner_base: 'type_of_alert' not found                                                                 
    Unexpected error during import with operation create for block.block.localgov_alert_banner_scarfolk: 'type_of_alert' not found
```

**Comment by andybroomfield** [comment]
Thanks for testing @Adnan-cds 
Not sure why the blocks would cause the issue, needs further investiagtion. 
Are you installing the theme alongside the alert banner module in the config sync, or just the module on its own (localgov_base / scarfolk already installed)?

**Comment by Adnan-cds** [comment]
> Are you installing the theme alongside the alert banner module in the config sync, or just the module on its own 

Just the localgov_alert_banner module and its related configs.  The themes got installed earlier as part of the *localgov* profile during a fresh site install.

**Comment by andybroomfield** [comment]
Just did a quick test and I noticed the type of alert field is installed after the block.
````
+------------+------------------------------------------------------------------------------+-----------+
|            | field.storage.localgov_alert_banner.visibility                               | Create    |
|            | field.storage.localgov_alert_banner.link                                     | Create    |
|            | localgov_alert_banner.localgov_alert_banner_type.localgov_alert_banner       | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.visibility           | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.link                 | Create    |
|            | block.block.localgov_alert_banner_base                                       | Create    |
|            | block.block.localgov_alert_banner_scarfolk                                   | Create    |
|            | field.storage.localgov_alert_banner.type_of_alert                            | Create    |
|            | field.field.localgov_alert_banner.localgov_alert_banner.type_of_alert        | Create    |
````

**Comment by andybroomfield** [comment]
@Adnan-cds I've posted an additional fix to try and address this. Its beacuse the `type_of_alert` field is not present when creating an instance of the alert banner block, as it's not imported yet. Although we need to look at the order, as its possible for users to delete the field (should they be able to?) then I've added a check to the sort in getCurrentBanners so it can be skipped over, alongside a test that confirms the banner block still loads and order is just date changed order.

This should allow your import to work, and then we can consider the issues this has raised.

File: tests/src/Kernel/AlertBannerBlockOrderTest.php [hunk 1]
```diff
@@ -160,4 +160,62 @@ public function testAlertBannerBlockOrder() {
...
+      $alert[] = $alert_entity->id();
+    }
+
+    // Create a block instance of the alert banner block.
+    $block_manager = $this->container->get('plugin.manager.block');
+    $config = [];
+    $plugin_block = $block_manager->createInstance('localgov_alert_banner_block', $config);
+
+    // Create and render the block and get the alert banner IDs as an array.
+    $plugin_block = $block_manager->createInstance('localgov_alert_banner_block', $config);
```
Comment (Adnan-cds) [inline tests/src/Kernel/AlertBannerBlockOrderTest.php]: Is this repetition of line 202 intentional?

Comment (andybroomfield) [reply tests/src/Kernel/AlertBannerBlockOrderTest.php]: Possibly not, I've just pushed an ammended commit.

Comment (Adnan-cds) [reply tests/src/Kernel/AlertBannerBlockOrderTest.php]: Thanks.

**Review by Adnan-cds — APPROVED** [review]
Works for me.  Many thanks for the prompt fix :)
